---
ruby_vers:   '2.3.1'
app_repo:    'https://github.com/mmolinac/P161Hi/raw/master'
app_name:    'sampleapp'
app_vers:    '1.0.4'
app_user:    'ruby'
app_user_pw: '$6$.w0GMQW.$CSnTx7PwcAMpIPklOXwkDDlZwb0Kl3JyWDRg1rDljd0lf.Q.Uv26xzk7Ki6rXiUQ7jfMxqqcY5VUJih7a6Khl0'
app_group:   'ruby'