# Debian / Ubuntu

  - name: Application user and group
    group:
      name: '{{app_group}}'
      state: present
    become: yes

  - user:
      name: '{{app_user}}'
      group: '{{app_group}}'
      shell: /bin/bash
      password: '{{app_user_pw}}'
      update_password: always
    become: yes

  - name: Apache server
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - apache2
      - libapache2-mod-php5
    become: yes

  # Register the sampleapp systemd service
  - service: name=apache2 enabled=yes state=started
    become: yes