---
# All hosts
- name: Update APT database
  hosts: all
  tasks:
    - apt:
        update_cache: yes
        cache_valid_time: 10800
        name: python-apt # for every host
      become: yes

# Database hosts
- hosts: db1
  become: true
  roles:
    - mysql-database

# Front-end hosts
- hosts: front1
  become: true
  roles:
    - rails-frontend
