# Debian / Ubuntu
  - name: Install MySQL server Debian
    apt: name={{item}} state=latest
    with_items:
      - mysql-server
      - python-mysqldb # Needed for configuring users
    become: yes

  - name: MySQL configuration
    template:
      src: "debian_my_cnf.j2"
      dest: /etc/mysql/my.cnf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart mysql-server
    become: yes

  - mysql_user:
      name: frontuser
      password: '12345'
      host: '192.168.5.%' # Permission to all hosts in the subnet
      priv: '*.*:ALL'
      state: present

  - service: name=mysql enabled=yes state=started
    become: yes