# Debian / Ubuntu

  # We'd like to use here 'apt_repository' but it's not possible
  # with ansible 2.0.0.1, so it seems.
  ##apt_repository:
  ##  repo: 'ppa:rael-gc/rvm'
  ##  codename: 'xenial' # workaround for https://github.com/ingomueller-net/ansible-java/commit/c805b8288007a687b5b058f1c746373b77999042

  # Repo for https://github.com/rvm/ubuntu_rvm
  - name: RVM repository and key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: F4E3FBBE
    become: yes

  - apt_repository:
      repo: deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu xenial main
      state: present
    become: yes

  - name: RVM and other Debian packages
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - rvm
      - software-properties-common # in order to add PPA repositories
      - mysql-client # to connect to DB servers
      - libmysqlclient-dev # required by MySQL Ruby gem
    become: yes

  # Now we'll install a ruby version as stated in:
  #   https://rvm.io/rubies/installing/
  - name: Ruby {{ruby_vers}} installation and registry with RVM
    shell: /usr/share/rvm/bin/rvm install {{ruby_vers}} && /usr/share/rvm/bin/rvm alias create default ruby-{{ruby_vers}} && /usr/share/rvm/bin/rvm use {{ruby_vers}} --default
    args:
      creates: /usr/share/rvm/rubies/ruby-{{ruby_vers}}/bin/ruby
    become: yes

  # Getting a list of installed gems
  - shell: PATH=$PATH:/usr/share/rvm/rubies/ruby-{{ruby_vers}}/bin /usr/share/rvm/rubies/ruby-{{ruby_vers}}/bin/gem list
    register: mygems
    changed_when: false
    become: yes

  - name: Installing Rails and other required gems
    shell: PATH=$PATH:/usr/share/rvm/rubies/ruby-{{ruby_vers}}/bin /usr/share/rvm/rubies/ruby-{{ruby_vers}}/bin/gem install {{item}}
    when: "'{{item}}' not in mygems.stdout"
    with_items:
      - rails
      - execjs
      - therubyracer
      - mysql2
      - rack
      - sprockets
      - railties
    become: yes

