# Debian / Ubuntu
  - name: RoR frontend basic deps on Debian
    apt: name={{item}} state=latest
    with_items:
      - software-properties-common # in order to add PPA repositories
      - mysql-client # to connect to DB servers
    become: yes

    # We'd like to use here 'apt_repository' but it's not possible
    # with ansible 2.0.0.1, so it seems.
    ##apt_repository:
    ##  repo: 'ppa:rael-gc/rvm'
    ##  codename: 'xenial' # workaround for https://github.com/ingomueller-net/ansible-java/commit/c805b8288007a687b5b058f1c746373b77999042

  # Repo for https://github.com/rvm/ubuntu_rvm
  - name: RVM repository and key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: F4E3FBBE

  - apt_repository:
      repo: deb http://ppa.launchpad.net/rael-gc/rvm/ubuntu xenial main
      state: present

  - name: RVM package
    apt:
      update_cache: yes
      name: rvm
      state: latest
    become: yes

  # Now we'll install a ruby version as stated in:
  #   https://rvm.io/rubies/installing/

  - name: Ruby 2.3.1 installation with RVM
    command: /usr/share/rvm/bin/rvm install 2.3.1
    args:
      creates: /usr/share/rvm/rubies/ruby-2.3.1/bin/ruby
    become: yes

  - name: Symlink to our Ruby version from /usr/bin/ruby
    file:
      src:  /usr/share/rvm/rubies/ruby-2.3.1/bin/ruby
      dest: /usr/bin/ruby
      state: link

  - name: Rails installation
    gem:
      name: rails
      state: present
      executable: /usr/share/rvm/rubies/ruby-2.3.1/bin/gem # env_shebang=yes
    become: yes

  - name: Installing gems required for Demo Application
    gem:
      name: '{{ item }}'
      state: present
      executable: /usr/share/rvm/rubies/ruby-2.3.1/bin/gem # env_shebang=yes
    with_items:
      - execjs # https://github.com/rails/execjs
      - therubyracer
    become: yes
